stages:
  - build
  - deploy

build:
  stage: build
  image: node:19
  script:
    - echo "Building the project"
    - cd frontend
    - npm ci
    - npm run build
  only:
    - merge_requests

deploy:
  stage: deploy
  image: node:19
  script:
    - echo "Deploying to Vercel"
    - cd frontend
    - sed -i 's/project2//g' vite.config.ts
    - cd src
    - sed -i 's/project2//g' main.tsx
    - cd ..
    - npx vercel --token $VERCEL_TOKEN --yes=n --prod
  environment:
    name: prod
  only:
    - main
  variables:
    VERCEL_TOKEN: $VERCEL_TOKEN
