stages:
  - lint
  - prettier
  - test
  - build
  - deploy

lint frontend:
  stage: lint
  image: node:19
  script:
    - echo "Linting the frontend"
    - cd frontend
    - npm ci
    - npm run lint
  only:
    - merge_requests

lint backend:
  stage: lint
  image: node:19
  script:
    - echo "Linting the backend"
    - cd backend
    - npm ci
    - npm run lint
  only:
    - merge_requests

prettier frontend:
  stage: prettier
  image: node:19
  script:
    - echo "Checking prettier frontend"
    - cd frontend
    - npm ci
    - npm run prettier:check
  only:
    - merge_requests

prettier backend:
  stage: prettier
  image: node:19
  script:
    - echo "Checking prettier backend"
    - cd backend
    - npm ci
    - npm run prettier:check
  only:
    - merge_requests

test:
  stage: test
  image: node:19
  script:
    - echo "Testing the project"
    - cd frontend
    - npm ci
    - npm run test:vitest
  only:
    - merge_requests

build:
  stage: build
  image: node:19
  script:
    - echo "Building the project"
    - cd frontend
    - npm ci
    - npm run build
  only:
    - merge_requests
