stages:
  - lint
  - prettier
  - test
  - build
  - deploy

lint:
  stage: lint
  image: node:19
  script:
    - echo "Linting the project"
    - cd frontend
    - npm ci
    - npm run lint
  only:
    - merge_requests

prettier:
  stage: prettier
  image: node:19
  script:
    - echo "Checking prettier"
    - cd frontend
    - npm ci
    - npm run prettiercheck
  only:
    - merge_requests

test:
  stage: test
  image: node:19
  script:
    - echo "Testing the project"
    - cd frontend
    - npm ci
    - npm run test:vitest
  only:
    - merge_requests

build:
  stage: build
  image: node:19
  script:
    - echo "Building the project"
    - cd frontend
    - npm ci
    - npm run build
  only:
    - merge_requests
